const ROUTES = {
  main: '/',
  addMoim: '/add-moim',
  detail: '/moim/:moimId',
  participationComplete: '/moim/participation-complete',
  login: '/login',
  modify: '/modify/:moimId',
  chat: '/chat',
  chattingRoom: '/chatting-room/:moimId',
  please: '/please',
  addPlease: '/please/creation',
  myPage: '/my-page',
  darakbangSelectOption: '/darakbang-select-option',
  darakbangSelect: '/darakbang-select',
  darakbangCreation: '/darakbang-creation',
  darakbangEntrance: '/darakbang-entrance',
  darakbangNickname: '/darakbang-nickname',
  darakbangLanding: '/darakbang-landing',
  darakbangManagement: '/darakbang-management',
  darakbangMembers: '/darakbang-members',
  darakbangInvitation: '/darakbang-invitation',
  darakbangInvitationRoute: '/darakbang-invitation-route',
};

export default ROUTES;
