export const meetings = [
  {
    id: 1,
    title: '축구 하실 사람?',
    date: '7월 15일 오후 2시',
    location: '서울 마포구 독막로 96 1층',
    maxParticipants: 4,
    currentParticipants: 2,
  },
  {
    id: 2,
    title: '축구 하실 사람?',
    date: '7월 15일 오후 2시',
    location: '서울 마포구 독막로 96 1층',
    maxParticipants: 4,
    currentParticipants: 2,
  },
  {
    id: 3,
    title: '축구 하실 사람?',
    date: '7월 15일 오후 2시',
    location: '서울 마포구 독막로 96 1층',
    maxParticipants: 4,
    currentParticipants: 2,
  },
  {
    id: 4,
    title: '축구 하실 사람?',
    date: '7월 15일 오후 2시',
    location: '서울 마포구 독막로 96 1층',
    maxParticipants: 4,
    currentParticipants: 2,
  },
  {
    id: 5,
    title: '축구 하실 사람?',
    date: '7월 15일 오후 2시',
    location: '서울 마포구 독막로 96 1층',
    maxParticipants: 4,
    currentParticipants: 2,
  },
  {
    id: 6,
    title: '축구 하실 사람?',
    date: '7월 15일 오후 2시',
    location: '서울 마포구 독막로 96 1층',
    maxParticipants: 4,
    currentParticipants: 2,
  },
  {
    id: 7,
    title: '축구 하실 사람?',
    date: '7월 15일 오후 2시',
    location: '서울 마포구 독막로 96 1층',
    maxParticipants: 4,
    currentParticipants: 2,
  },
];
