name: frontend-deploy

on:
  push:
    branches:
      - develop-frontend

jobs:
  deploy:
    runs-on: [self-hosted, develop]

    steps:
      - name: deploy
        run: |
          cd ~/deploy && ./deploy-fe-dev.sh
